// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-ecs-agent/agent/stats/statsretriever (interfaces: StatsRetriever)

// Package mock_statsretriever is a generated GoMock package.
package mock_statsretriever

import (
	reflect "reflect"

	types "github.com/docker/docker/api/types"
	gomock "github.com/golang/mock/gomock"
)

// MockStatsRetriever is a mock of StatsRetriever interface
type MockStatsRetriever struct {
	ctrl     *gomock.Controller
	recorder *MockStatsRetrieverMockRecorder
}

// MockStatsRetrieverMockRecorder is the mock recorder for MockStatsRetriever
type MockStatsRetrieverMockRecorder struct {
	mock *MockStatsRetriever
}

// NewMockStatsRetriever creates a new mock instance
func NewMockStatsRetriever(ctrl *gomock.Controller) *MockStatsRetriever {
	mock := &MockStatsRetriever{ctrl: ctrl}
	mock.recorder = &MockStatsRetrieverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStatsRetriever) EXPECT() *MockStatsRetrieverMockRecorder {
	return m.recorder
}

// GetNetworkAdapterStatisticsPerContainer mocks base method
func (m *MockStatsRetriever) GetNetworkAdapterStatisticsPerContainer(arg0 string, arg1 uint64) (*types.NetworkStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkAdapterStatisticsPerContainer", arg0, arg1)
	ret0, _ := ret[0].(*types.NetworkStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkAdapterStatisticsPerContainer indicates an expected call of GetNetworkAdapterStatisticsPerContainer
func (mr *MockStatsRetrieverMockRecorder) GetNetworkAdapterStatisticsPerContainer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkAdapterStatisticsPerContainer", reflect.TypeOf((*MockStatsRetriever)(nil).GetNetworkAdapterStatisticsPerContainer), arg0, arg1)
}
